### ISSUE TITLE
Bluetooth AD type 0x0d is already in use

### ISSUE THREAD

**Issue by Vudentz** [opendroneid/specs#1] opened 2019-04-17 06:48 UTC
0x0D | «Class of Device» 

https://www.bluetooth.com/specifications/assigned-numbers/generic-access-profile

Usually Bluetooth beacons use the following types:

0x16 | «Service Data - 16-bit UUID»
0xFF | «Manufacturer Specific Data»

Though these requires extra 2 bytes compared to using a dedicated type, but getting a dedicated type for a beacon spec is probably not something Bluetooth SIG is likely to allow as the AD type domain is rather short (1 byte).

Even with use of Manufacturer Data we still need a manufacturer ID to be added, luckly there exists a way to request UUIDs for Standards Development Organizations:

https://www.bluetooth.com/specifications/assigned-numbers/16-bit-uuids-for-sdos

**Comment by Vudentz** [comment] 2019-04-17 06:53
@gabrielcox ^

**Comment by gabrielcox** [comment] 2019-04-18 16:29
0x0D is the "app code" -- something we added within the mfg namespace.  It's the first byte within the MFG specific data.
The type code is 0xFF (as you described above).

So the AD Flags (onward) looks like this:
....<ad-type=0xff (mfg specific)><mfg id=0200h><app=0x0D><counter=xx><data>....

It's not clear to me that you can use an SDO UUID as the MFG ID.  Do you have any info otherwise?  (I would really rather use the SDO UUID than our company code.

Gabriel.

**Comment by pzboyz** [comment] 2019-04-18 16:42
You use the SDO UUID in place where you would use it as a UUID for a Primary Service.

**Comment by gabrielcox** [comment] 2019-04-18 22:25
sorry, I miss-typed:  Current spec for AD is as below.  (now including mfgid).

....<ad-type=0xff (mfg specific)><mfgid=0x0002><app=0x0D><counter=xx><ODID-Data...>....

**Comment by gabrielcox** [comment] 2019-04-18 23:02
@Vudentz now that you see that 0x0D is within the "mfg data", do you still see this as a spec bug?

@pzboyz We'll take a look at your suggestion.

**Comment by gabrielcox** [comment] 2019-04-19 04:09
@pzboyz -- I'll take a deeper look at "Service Data" in the CSS.

**Comment by Vudentz** [comment] 2019-04-19 10:14
> @Vudentz now that you see that 0x0D is within the "mfg data", do you still see this as a spec bug?

Should be alright if it is within the AD payload itself then is up to spec to define... Regarding the SDO UUID that is preferred over Manufacturer data as that needs a manufacturer ID which means each manufacturer would have to advertise with their own ID or fake the ID to be the same (there could be legal implications of doing the later), so I would really recommend doing the Service Data (0x16) with the SDO UUID.

**Comment by gabrielcox** [comment] 2019-04-19 13:58
@Vudentz , Agreed.  I'm requesting an SDO ID as we speak and will experiment with this.  It was not clear to me before that you could get the same single message payload flexibility as you do with mfg specific, but it's clear to me now.  We have the existing spec working with TI, Nordic, Android, iOS as it is so we'll just need to validate.  I expect it will work fine (and have a better namespace org).

Thanks again for the feedback from both of you (@Vudentz , @pzboyz ) .

Also, if any of you are doing open source implementations (or are interested in doing so), please send me a DM.  I run an "early developers" conference call and slack channel and would be happy to promote any OS projects implementing Open Drone ID.

**Comment by gabrielcox** [comment] 2019-06-01 00:04
This issue is mostly a duplicate of the previous -- I'll post the proposed doc update for comment.
Please indicate your opinion on the proposed doc update:
![image](https://user-images.githubusercontent.com/13051211/58740617-2a6c1380-83c6-11e9-87aa-464ad9da5c4f.png)

**Comment by friissoren** [comment] 2019-09-02 06:18
Let's close this issue. A dedicated Service UUID (0xFFFA) has been assigned to the ASTM standardization organization and this has been taken into use in the standard. The Application Code 0x0D = Open Drone ID then makes OpenDroneID unique within that namespace.

https://www.bluetooth.com/specifications/assigned-numbers/generic-access-profile/  => 0x16
https://www.bluetooth.com/specifications/assigned-numbers/16-bit-uuids-for-sdos/ => 0xFFFA

**Closed as completed** 2019-09-04 06:25 UTC
